### ISSUE TITLE
Add timelock to unstake function in Fragment.sol

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#105]
Add a timelock into [Fragment.sol/unstake function](https://github.com/fragcolor-xyz/hasten-contracts/blob/2ddee57fdd1e05192638298e4ba327e6b414a432/contracts/Fragment.sol#L505) to prevent user to unstake fragments until end of stacking period.

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/105?planning-poker) with ZenHub @aang114 @sinkingsugar

**Comment by sinkingsugar** [comment]
This is more complex:

## Locking
### Standard Periods

^f159fa

* **2 weeks**
  * Tickets bonus = 0%
  * Nova bonus = 0%
* **1 month**
  * Tickets bonus = 5%
  * Nova bonus = 2%
* **3 months**
  * Tickets bonus = 12%
  * Nova bonus = 5%
* **6 months**
  * Tickets bonus = 25%
  * Nova bonus = 10%
* **1 year**
  * Tickets bonus = 50%
  * Nova bonus = 20%

#### Extras
People holding certain Fragments (e.g. Ambal, Fragnova, RR) can have further bonuses TBD. As well as partner NFTs on other chains etc.

## ETH Smart Contracts
- [x] Add a lock time parameter to the lock function using ![[#^f159fa]]
- [x] Standard Periods need to be an enum
- [x] Unlock has to fail if the period has not elapsed
- [x] Fix events to follow this new structure
- [x] Write simple tests

**Comment by sinkingsugar** [comment]
This task should be in hasten-contracts repo (we should rename that also)

**Comment by alebaffa** [comment]
@sinkingsugar by `lock` and `unlock` functions you mean `stake()` and `unstake()` right?

**Comment by sinkingsugar** [comment]
No I mean lock and unlock of clamor branch of hasten-contracts repo.
