### ISSUE TITLE
Gamer store - get fragments details query call 

### ISSUE THREAD

**Issue by paulinechi** [fragcolor-xyz/clamor#109]
Acceptance criteria:
- [ ] The query call `api.query.fragments.fragments([id])` should return information include: fragment category, tags, creator, owner, metadata, references, include cost

**Comment by paulinechi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/109?planning-poker) with ZenHub @aang114 @alebaffa @sinkingsugar

**Comment by sinkingsugar** [comment]
those queries read storage directly, so there is nothing to implement, just need to put the pieces together
https://github.com/fragcolor-xyz/clamor/blob/712223ddac348d22de52af01fa317f0e88316417/pallets/fragments/src/lib.rs#L195
