### ISSUE TITLE
Update sync_partner_contract

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#114]
Following #105

**Comment by alebaffa** [comment]
@sinkingsugar There is also the struct `EthLockUpdate` to update with the `timelock` field. In case the event is a `Lock`, it will get the time duration taken from the Ethereum event log, but in case the event is `Unlock`, I am giving a value of zero to this field. Is it ok for you?

**Comment by sinkingsugar** [comment]
> @sinkingsugar There is also the struct `EthLockUpdate` to update with the `timelock` field. In case the event is a `Lock`, it will get the time duration taken from the Ethereum event log, but in case the event is `Unlock`, I am giving a value of zero to this field. Is it ok for you?

Well I don't think we need a time value in unlock.
also Lock should be the enum, not the actual time maybe?

**Comment by alebaffa** [comment]
It seems that also the function `internal_lock_update` needs to be updated if we want also our internal Locked event to contain the lock period:

 `Self::deposit_event(Event::Locked { eth_key: sender, balance: amount }); `

Should we add this information in it too?
