### ISSUE TITLE
Implement ticket and nova minting on sync_partner_contract

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#115]
When a new event arrives we need to:

- [x] assign ticket to the associated H160 account (no matter if linked already or not to a FN account)
- [ ] assign some nova (20% for now) and start nova vesting as well (no matter if linked already or not to a FN account)

**Comment by alebaffa** [comment]
@sinkingsugar This is basically a task of issue #117 . I put it as a dependency, basically.

**Comment by alebaffa** [comment]
Need to check out Substrate's `pallet-vesting` for vesting of NOVA: https://docs.rs/pallet-vesting/latest/pallet_vesting/ , https://github.com/paritytech/substrate/blob/master/frame/vesting/src/lib.rs .

**Comment by sinkingsugar** [comment]
> Need to check out Substrate's `pallet-vesting` for vesting of NOVA: https://docs.rs/pallet-vesting/latest/pallet_vesting/ , https://github.com/paritytech/substrate/blob/master/frame/vesting/src/lib.rs .

I don't think it has anything to do with it, I mean our behaviour is rather different 🤔 prefer have full control.
