### ISSUE TITLE
Implement tickets

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#117]
As part of accounts pallet, implementing the `Fungible` trait.

**Comment by sinkingsugar** [comment]
Syncing with the ETH network via pallet_accounts, we should mint tickets according to the ETH smart contract.
To be honest this could also include minting NOVA as well.

**Comment by sinkingsugar** [comment]
Part of this task should be swapping into our substrate fork which allows assets to be untradeable.

**Comment by alebaffa** [comment]
- [x] Calculate lock period
- [ ] Implement price oracle to get USD price (Chainlink or others)
- [ ] Mint Tickets and NOVA according to the lock period and bonus calculation
- [x] Implement the untreadable Trait from substrate fork (pallet assets).

**Comment by sinkingsugar** [comment]
This was estimated 13 but ended being in so many sprints. We need to retrospect here. cc @ZerusD
