### ISSUE TITLE
Replace stake/unstake in protos with a single tickets spending call

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#118]
We don't stake/unstake anymore now we instead need to lock tickers in a Proto and track time, after X period (as propagated from ETH contract -> pallet assets) we burn them/remove them from the Proto. To refresh users need to literally spend again tickets.

**Comment by sinkingsugar** [comment]
This is what I did

**Comment by aang114** [comment]
@sinkingsugar , isn't this done?

**Comment by sinkingsugar** [comment]
Yeah `curate` but I don't think it's 100% complete.

**Comment by alebaffa** [comment]
I would close this ticket, as `curate` function has been done, and specify what is still needed in other issues, ok?
I already created #200 as a starter.
