### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#129]
get_protos has a wrong statement in the docs text.

https://github.com/fragcolor-xyz/clamor/blob/8e9148aee01ad7e537c1c78c288ff3bb642e0ff9/pallets/protos/src/lib.rs#L856

**Comment by alebaffa** [comment]
Lib account has some TODO regarding documentation.

**Comment by alebaffa** [comment]
Please make an estimate of this before the Sprint is finished.

**Comment by aang114** [comment]
> Please make an estimate of this before the Sprint is finished.

This is done: https://github.com/fragcolor-xyz/clamor/blob/devel/pallets/protos/src/lib.rs#L1108-L1114. Could you close this issue? Thanks
