### ISSUE TITLE
Integrate external DEX pallet into Clamor

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#145]
Pablo pallet from Composable Finance: https://github.com/ComposableFi/composable/tree/main/frame/pablo provides interesting features that is worth evaluating.

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/145?planning-poker) with ZenHub @aang114 @sinkingsugar

**Comment by alebaffa** [comment]
`pallet-pablo` has dependencies with
- 7 homemade internal pallets (`composable-maths`, `composable-support`, `composable-test-helpers`, `composable-traits`, `currency-factory`, `fnft`, staking-rewards`)
- 2 forked pallets from FRAME:
    - `pallet-proxy `called `account-proxy` to _enable programmatic access through a standard trait_
    - `pallet-assets` _to provide implementations for common currency traits and functionality for handling transfers and minting. E.g. from [orml](https://docs.rs/orml-traits) or [frame_support](https://github.com/paritytech/substrate/tree/master/frame/support)_

The two forked pallets need to be carefully reviewed. Mostly the `pallet-assets` since we also forked it.

**Comment by sinkingsugar** [comment]
That's a lot of mods... a bit scary.. Can we find a simpler AMM alternative?

**Comment by alebaffa** [comment]
Yeah it seems definitely complicated. Let me see if a simpler one is in my list.

**Comment by sinkingsugar** [comment]
can you check https://hydradx.io/ btw?

**Comment by alebaffa** [comment]
To check this:  [https://github.com/galacticcouncil/HydraDX-node/tree/master/pallets/omnipool ](https://github.com/galacticcouncil/HydraDX-node/tree/master/pallets/omnipool )
