### ISSUE TITLE
Perform quick and preliminary data validation

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#154]
From TODO in runtime: https://github.com/fragcolor-xyz/clamor/blob/34767ffd86d5d7db7f6f02e2d02ee4662005efdb/runtime/src/lib.rs#L713 .

> We want to prevent polluting blocks with a lot of useless invalid data.

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/154?planning-poker) with Zenhub @aang114 @sinkingsugar

**Comment by sinkingsugar** [comment]
Status @aang114 ?

**Comment by aang114** [comment]
> Status @aang114 ?

Need to add the check for multisig extrinsics, then it'll be done
