### ISSUE TITLE
Test `check_license()` in pallet protos

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#155]
https://github.com/fragcolor-xyz/clamor/blob/34767ffd86d5d7db7f6f02e2d02ee4662005efdb/pallets/protos/src/lib.rs#L817 .

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/155?planning-poker) with Zenhub @aang114 @alebaffa @sinkingsugar
