### ISSUE TITLE
Add features into `create_account()` in pallet-fragments

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#160]
> // TODO Make owner pay for deposit actually!
> // TODO setup proxy

https://github.com/fragcolor-xyz/clamor/blob/d0b9ef9e4c750881e5c84afbca8a3db3f5c58c43/pallets/fragments/src/lib.rs#L979

Maybe this needs some discussions? @aang114  @sinkingsugar

**Comment by sinkingsugar** [comment]
Yeah, undecided actually
