### ISSUE TITLE
Write a new RPC in Pallet Protos that Retrieves all the "Ancestor References" of a Proto and all the "Descendent References" of a Proto

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/clamor#165]

**Comment by alebaffa** [comment]
Please, make an estimate of this one before the Sprint is finished. It should have been done before, but better late than never. At least we track this work.

**Comment by aang114** [comment]
This is done: https://github.com/fragcolor-xyz/clamor/pull/168. But I will only open a PR after #148 is merged 😅
