### ISSUE TITLE
Add detach into Fragments

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#176]
Need to discuss, @sinkingsugar @aang114 .

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/176?planning-poker) with Zenhub @aang114 @sinkingsugar

**Comment by sinkingsugar** [comment]
We decided to not remove but instead simply add it to Fragments as well.
