### ISSUE TITLE
Write tests for pallet detach

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#177]
There are no unit tests for this pallet. Need to make them.

**Comment by alebaffa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/177?planning-poker) with Zenhub @aang114

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/177?planning-poker) with Zenhub @alebaffa @sinkingsugar
