### ISSUE TITLE
RPCs should receive/return Clamor Account IDs in SS58 format

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/clamor#196]
Currently, it is returning/receiving Clamor account IDs in Hexadecimal format.

**P.S**

You can use this trait to convert to/from SS68 format: https://paritytech.github.io/substrate/master/sp_core/crypto/trait.Ss58Codec.html#method.to_ss58check

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/196?planning-poker) with Zenhub @aang114 @sinkingsugar

**Comment by aang114** [comment]
I have decided to just return the hexadecimal representation of the returned Clamor Account IDs instead of the SS58 representation.

This is because:
- The trait `Ss58Codec` of our `T::AccountId` is only implemented if the feature flag is `std`
- Also Shawn Tabrizi recommended to the OP of this Stackoverflow post against converting to SS58 in the Runtime and to convert it in JavaScript itself: https://stackoverflow.com/questions/66285787/how-do-i-convert-frames-accountid-to-network-specific-ss58
