### ISSUE TITLE
Detach for real

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#202]

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/202?planning-poker) with Zenhub @aang114 @alebaffa @sinkingsugar

**Comment by sinkingsugar** [comment]
hmm what's this issue about anyway? I dont remember, can we expand before spending points?

**Comment by alebaffa** [comment]
@sinkingsugar At the moment we only emit a signature that's signed by EthereumAuthorities.
If there's nothing more to add, I can close this one.

**Comment by alebaffa** [comment]
We'll discuss it later on. I put it on new issues.
