### ISSUE TITLE
Metadata data size should be strictly limited

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#208]
Figure reasonable limits and apply limits in `validate_transaction` and enforce further in the extrinsic itself.

**Comment by alebaffa** [comment]
There is already the issue #154 for validate_transaction. I think it's better to either use that one only or I can create an Epic so that we can add multiple issues into it (I guess there will be many issues related to different limitations that could come up over the time).

**Comment by sinkingsugar** [comment]
I think this is very much another thing, which needs to be kept separate and actually more urgent. Just happens to be part of that issue as well.

**Comment by sinkingsugar** [comment]
Also solving this issue is very trivial.
We need a discussion here to understand reasonable limits, this issue is about finding reasonable limits as mentioned on discord.

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/208?planning-poker) with Zenhub @aang114 @sinkingsugar

**Comment by sinkingsugar** [comment]
What happened to this issue? Why it's not in the sprint?

**Comment by alebaffa** [comment]
@sinkingsugar it's included in this one #205. Karan is working on it.

**Comment by sinkingsugar** [comment]
In that case #205 is blocked by #222

**Comment by alebaffa** [comment]
So, considered that the hard limit found in #222 is 3.75MB, i have very rarely seen a metadata file (i.e. json typically) to be this big (except for files resulting from production logs/processes, which is not the case for us here).
I created locally a JSON file contaning 2733 lines of
```json
{
 "employee": {  
        "name":       "sonoo",   
        "salary":      56000,   
        "married":    true  
    },
}
```
and the file is ~70KB.

So, I think that probably a range between [50-100] KB can be considered a reasonable upper limit for our metadata files, it is well below the block limit and also leaves space for other files.

**Comment by sinkingsugar** [comment]
Metadata here can be anything, videos, images etc.

**Comment by sinkingsugar** [comment]
Status? @aang114

**Comment by aang114** [comment]
> Status? @aang114

I've implemented the logic (in PR https://github.com/fragcolor-xyz/clamor/pull/205). But the PR itself isn't done.

Will be completing this PR after I'm done with the Collection contracts
