### ISSUE TITLE
Hash Shortner

### ISSUE THREAD

**Issue by jwchoo-81** [fragcolor-xyz/clamor#216]
**Is your feature request related to a problem? Please describe.**

currently, we are using the hexadecimal value which is relatively long and a little hard to identify and use.

**Describe the solution you'd like**

We would like some form of alias/shortner to be mapped over to the particular proto that is on chain.

**Describe alternatives you've considered**

We've considered using a database that maps the proto hexadecimal value to a shortened value that was randomly generated.

**Additional context**

**Comment by alebaffa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/216?planning-poker) with Zenhub @aang114 @sinkingsugar

**Comment by alebaffa** [comment]
Closing this because included in #226.
