### ISSUE TITLE
Clusters

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#219]
# Overview

* New pallet, `pallet-clusters`
* The cluster is like a **Discord** guilds
  * It has roles
  * roles have members assigned
  * you **CAN** have multiple roles assigned
  * roles can have rules assigned
* Change `upload` function on pallet protos
  * Can take a cluster, optionally

### First set, Q4 2022
  * royalties cut %
  * ability to license certain proto based on role
  * a cluster can have an account or multiple accounts

### Second set, Q1 2023
* voting system

# Implementation

## Calls
* `(New-Cluster name)`
* `(New-Role cluster role-name role-settings)`
* `(Add-Member cluster role-name member-data)`
* `(Del-Member cluster role-name member-data)`
* `(Edit-Role cluster role-name role-settings)` 
  * In the future edit can be set to be approved by majority or so of cluster members or something

**Comment by ZerusD** [comment]
We need a way for a partner/platform to automatically have a role included in a Cluster when it is created on their platform or using their asset. This partner role will be used to collect their fees/cut from any transaction involving.
The % designated for the partner role should be customizable and the role itself should not be able to be removed by the Cluster creator.
Example: any Cluster created in Narraio will automatically have the "Narraio" role which will collect a % and could offer some permissions in the platform

**Comment by alebaffa** [comment]
@ZerusD So, following the calls implementation specs from @sinkingsugar , wouldn't it be better to first create the list of Roles and then create a new Cluster, passing the roles into it too (along with its name)? This way it is up to the partner UI to make the calls in the correct order (e.g. create a "partner-role", then create a Cluster with that role). So the flow would be

`(New-Role role-name role-settings)`
`(New-Cluster name roles)`

**Comment by alebaffa** [comment]
OK I see.
This could be done by adding the `AccountId` in the storage of a Role. 
This can allow the execution of the function `(Edit-Role cluster role-name role-settings)` only to the `AccountId` that is owner of that Role. 

When a user _creates_ a cluster from the partner's platform, behind the scene the calls made by the platform would be:
1. `(New-Cluster name)` associated to the `user.AccountId`
2. `(New-Role cluster role-name role-settings)` associated to the `partner.AccountId`

Sounds good, @sinkingsugar @ZerusD ?

**Comment by sinkingsugar** [comment]
> OK I see.
> 
> This could be done by adding the `AccountId` in the storage of a Role. 
> 
> This can allow the execution of the function `(Edit-Role cluster role-name role-settings)` only to the `AccountId` that is owner of that Role. 
> 
> 
> 
> When a user _creates_ a cluster from the partner's platform, behind the scene the calls made by the platform would be:
> 
> 1. `(New-Cluster name)` associated to the `user.AccountId`
> 
> 2. `(New-Role cluster role-name role-settings)` associated to the `partner.AccountId`
> 
> 
> 
> Sounds good, @sinkingsugar @ZerusD ?

As mentioned during the meeting, not really. Let's leave it out and create a new story please 🙏
