### ISSUE TITLE
pallet alias

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#220]
### In short
In order to fulfil our vision of being the Layer X, where X also meaning User experience we need a way to address items, protos, fragments, anything, on our chain in a very short and compact form.
This gives us a couple of opportunities including spinning possible economic value as well if done right.

We introduce a new pallet with the following functionalities
`create_namespace(origin: ..., name: String)`
`update_alias(origin: ..., namespace: Namespace, name: String, target: LinkTarget)`
`update_root_alias(origin: ..., name: String, target: LinkTarget)`

where `LinkTarget` for now can be:
* Proto
* Fragment
* AccountId

and `update_root_alias` requires a sudo origin to be called

### The final result
`dc/batman` -> pointing to a **proto** with a functional Batman asset owned officially and provable on chain by DC.

### Sidequests
Remove pallets: identity and indices in the process as we don't need them anymore.

**Comment by sinkingsugar** [comment]
I added the spec @alebaffa

**Comment by sinkingsugar** [comment]
Also I don't think it needs to be an epic but you can manage

**Comment by alebaffa** [comment]
I will create a new issue to be included in the existing epic #198 .
