### ISSUE TITLE
Determine hard limits

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#222]
Determine data hard limits in terms of amount of bytes we can upload per block and determine as well how to fine grain tune it.
The measure is bytes, I don't care weight.

**Comment by sinkingsugar** [comment]
Urgent to do on the side of sprint tasks.

**Comment by alebaffa** [comment]
@sinkingsugar The hard limit is controled by the BlockLenght, which is set in the runtime [here](https://github.com/fragcolor-xyz/clamor/blob/de41d2a351d4c24a8b3e390427b7ca848162bf85/runtime/src/lib.rs#L220):

```rust
pub RuntimeBlockLength: BlockLength = BlockLength::max_with_normal_ratio(5 * 1024 * 1024, NORMAL_DISPATCH_RATIO);
```
with the `NORMAL_DISPATCH_RATIO` being the variable that controls the _Normal_ extrinsics (the other ones are _initialization_ that take 10% and _Operational_ that take what remains (100 - 75 - 10 = 15%).
```rust
/// We assume that ~10% of the block weight is consumed by `on_initialize` handlers.
/// This is used to limit the maximal weight of a single extrinsic.
const AVERAGE_ON_INITIALIZE_RATIO: Perbill = Perbill::from_percent(10);
/// We allow `Normal` extrinsics to fill up the block up to 75%, the rest can be used
/// by  Operational  extrinsics.
const NORMAL_DISPATCH_RATIO: Perbill = Perbill::from_percent(75);
```
So, the hard limit in bytes is 75% of `(5 * 1024 * 1024)` = 3,932 MiB so 3.75MB.
This has also been tested by @aang114 locally trying to upload files up to these limits.

Changing this limit does not have impacts on the block duration (i.e. block weight, also tested locally by me just to be sure).

**Comment by alebaffa** [comment]
As a reference: [https://github.com/paritytech/substrate/blob/master/frame/system/src/limits.rs#L121-L194](https://github.com/paritytech/substrate/blob/master/frame/system/src/limits.rs#L121-L194)

**Comment by sinkingsugar** [comment]
Thank you @alebaffa , before doing anything we need to do an heavy refactor on many calls storing in the live state using unbounded vectors, need to change to use boundedvectors of a fixed len.
