### ISSUE TITLE
Refactor to use BoundedVec in extrinsics signature 

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#225]
Need to review where `Vec<u8>` is used in our code and replace them with `BoundedVec`, whenever the data is stored in the live state.

**Comment by aang114** [comment]
what does "live state" mean?

**Comment by alebaffa** [comment]
Storage.

**Comment by alebaffa** [comment]
Main parts that need to be checked:

- `pallet-fragments`: metadata size (key and data)
- `pallet-oracle`: data and tags sizes

**Comment by sinkingsugar** [comment]
Anything that gets stored into the state should be bounded. This excludes blocks purely (proto upload data)

**Comment by sinkingsugar** [comment]
State @aang114 ?

**Comment by aang114** [comment]
Done
