### ISSUE TITLE
Optimize storage in pallet-clusters

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#240]
Need to optimize storage to avoid passing always through Cluster storage. 
One problem for example is that Members now is stored twice in Cluster, and potentally other times.

> We can remove role hash, we can just keep indices, then we should have a storage that is Member, Cluster as keys (double storage) and inside a vec of role indicies. Don't store any such info on this struct.

**Comment by sinkingsugar** [comment]
Done right @alebaffa ?
