### ISSUE TITLE
Refactor LinkTarget struct

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#249]
https://github.com/fragcolor-xyz/clamor/blob/8f93846dd00964aceebbb79d4c6cc25ea8ee78e2/pallets/aliases/src/lib.rs#L121

We need to wrap it into a struct and add a `block_number` field.
This is needed to understand if for example a game engine using an asset via alias needs to update the asset again if the link was changed. Basically the `block_number` is like a **version number**.

**Comment by alebaffa** [comment]
Closed as done in #250 .
