### ISSUE TITLE
One-Stop RPC for the Protos Asset Store

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#35]
- [x] `get_by_tags(tags: Vec<Tags>, owner: Option<ProtoOwner<T::AccountId>>, limit: u32, from: u32, desc: bool) -> Vec<Hash256>`
- [x] `get_metadata_batch(batch: Vec<Hash256>, keys: Vec<String>) -> Vec<Hash256>`

## `get_by_tags` notes
Fetch from `ProtosByTag` and filter values with `Iterator` trait.
### JS RPC Side:
`protos_getByTags`

## `get_metadata_batch` notes
About keys:
```
get_metadata_batch(vec!["0xSGJSH"], vec!["json_description", "image"])
```
What happens after calling this is:
We fetch from ipfs each, json desc, and binary image

**Comment by aang114** [comment]
I've finished implemented the 2 Custom RPC functions (#38). 

Let me know what you think. Thanks
