### ISSUE TITLE
Get Rustdocs online

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#36]
#34 

- [x] Test docs in CI

**Comment by aang114** [comment]
#37

I have added a check for rustdocs in PR #37.

**Comment by sinkingsugar** [comment]
This is done right?

**Comment by aang114** [comment]
Yes

**Comment by aang114** [comment]
@sinkingsugar Actually, I can't find "clamor" on crates.io?

**Comment by sinkingsugar** [comment]
Yea you are right. We merged generating but not pushing.

**Comment by sinkingsugar** [comment]
@aang114 turns out we cannot publish on crates.io because we use "dev" versions of crates not on crates.io.
We need to use the same method chainblocks repo uses and use nft.storage or so to self publish our generated docs.
Could you check with @Kryptos-FR quickly to get a fast overview on how he did with chainblocks docs?
Basically we can add simply at end of CI docs step, the self publishing bit.

**Comment by sinkingsugar** [comment]
Where is this published @aang114 ?
We need to integrate it into some public facing page from our website as next step.

**Comment by sinkingsugar** [comment]
Please write new story accordingly @aang114 ? (public publishing)

**Comment by aang114** [comment]
done
