### ISSUE TITLE
Create Clamor architecture guide

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/clamor#47]
**Pitch**
As a developer new to Fragnova, I want to access the Clamor architecture guide so that I may be able to use Clamor better in my game development projects as well as contribute code and docs to this project.

**Acceptance criteria**
The architecture guide must
- [ ] Explain all the internal components of the Clamor networking stack & protocol
- [ ] Explain the Clamor implementation details and how its based on Substrate

**Additional Context**
This architecture guide must be hosted on `https://docs.fragcolor.xyz/architecture-guides/...`

**Comment by satendrapalsingh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/47?planning-poker) with ZenHub @guusw @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
Clamor is not used by game projects (directly). This issue needs to be reviewed. I think it can just be in the scope of the readme.

**Comment by satendrapalsingh** [comment]
For now, as suggested, I have included a brief introduction to Clamor in the README itself (issue #51 , PR #65).
This issue is a more detailed developer-oriented documentation that can be taken up later.
