### ISSUE TITLE
Categories & Tags

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#48]
Users should be able to browse and search Protos by categories and tags.
Where a category encompasses a more broad set and tags can narrow down to different subset of an asset.

**Comment by sinkingsugar** [comment]
@aang114 I think I briefed you about this but I didn't see this included in the RPC PR, I think we can keep the task separate btw. But making sure that is the case.

**Comment by aang114** [comment]
> @aang114 I think I briefed you about this but I didn't see this included in the RPC PR, I think we can keep the task separate btw. But making sure that is the case.

Yes, this has not been done yet.

**Comment by sinkingsugar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/48?planning-poker) with ZenHub @aang114 @Kryptos-FR @paulinechi
