### ISSUE TITLE
Outline and document necessary steps to setup clamor testnet with multiple nodes.

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#55]

**Comment by satendrapalsingh** [comment]
Where should this guide be hosted? On https://docs.fragcolor.xyz/ or should be added to Clamor's README?

**Comment by satendrapalsingh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/55?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
This is not for you @satendrapalsingh and can be closed.

**Comment by satendrapalsingh** [comment]
> This is not for you @satendrapalsingh and can be closed.

Oh, alright! Thanks Gio.
