### ISSUE TITLE
Implement NOVA vesting following locked FRAG

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#56]
Users need to receive NOVA yield for their FRAG lock (on ETH)

**Comment by sinkingsugar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/56?planning-poker) with ZenHub @guusw @Kryptos-FR @satendrapalsingh

**Comment by alebaffa** [comment]
Closing as duplicate of #115 .
