### ISSUE TITLE
Dynamically retrieve types to create apiPromise.

### ISSUE THREAD

**Issue by paulinechi** [fragcolor-xyz/clamor#63]
Able to dynamically retrieve types to create apiPromise.

**Comment by paulinechi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/63?planning-poker) with ZenHub @guusw @Kryptos-FR @satendrapalsingh @sinkingsugar

**Comment by sinkingsugar** [comment]
We don't need dynamic.
Let's have protos repo as npm dependency and a json file in it.

**Comment by paulinechi** [comment]
PR: https://github.com/fragcolor-xyz/protos/pull/3

**Comment by paulinechi** [comment]
PR merged by Giovanni
