### ISSUE TITLE
Add the option to pass in parameter available in getProtos method

### ISSUE THREAD

**Issue by paulinechi** [fragcolor-xyz/clamor#66]
Add the option to pass in parameter **available** (true / false) in getProtos method

**Comment by sinkingsugar** [comment]
added in #69

**Comment by paulinechi** [comment]
Should be able to pass in `available` as a parameter and retrieve protos dynamically. 

For example:` let result = await api.rpc.protos.getProtos({categories: {text: json}, available: true, from:0, limit: 9}); `

The limit should be on the result of both category and availability.
