### ISSUE TITLE
Add secondary sales of Fragments

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#72]
Currently `buy` works only for *creator to new owner* sales. Not for *owner to new owner* sales.
Owners will definitely want to set for sale Fragments and other users need to be able to buy them.

**Comment by sinkingsugar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/72?planning-poker) with ZenHub @aang114 @guusw @Kryptos-FR

**Comment by aang114** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/72?planning-poker) with Zenhub @alebaffa

**Comment by aang114** [comment]
@sinkingsugar , I can take over this if you want?

**Comment by sinkingsugar** [comment]
> @sinkingsugar , I can take over this if you want?

please
