### ISSUE TITLE
Optimize the RPC `getProtos()`

### ISSUE THREAD

**Issue by paulinechi** [fragcolor-xyz/clamor#73]
The current getProtos call returns image hash, json_description hash, owner hash and include_cost, will need to call api.query.identity.identityOf, api.query.protos.protos and api.query.protos.protoCurations to get proto details, would be faster if we can get them in one call.

Acceptance criteria:
- [ ] api.query.identity.identityOf
- [ ] api.query.protos.protos
- [ ] api.query.protos.protoCurations

**Comment by paulinechi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/73?planning-poker) with ZenHub @aang114 @sinkingsugar @Kryptos-FR

**Comment by alebaffa** [comment]
@paulinechi @aang114 is this issue still valid?

**Comment by paulinechi** [comment]
> @paulinechi @aang114 is this issue still valid?

Yes, if this can be implemented it'll help improve the loading speed of the proto detail page. 

For the next sprint I'll work on refactoring the fetchProtoDetail function and try to improve the performance, maybe we can revisit this issue after that to decide if this is still needed. If it's fast enough after doing the optimization on the frontend we can probably close it or give it a low priority.

**Comment by alebaffa** [comment]
Ok, let's do it. Thank you!
