### ISSUE TITLE
Refactor process_detach_requests

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#75]
It's a big monolith, it can be split and refactored nicely

**Comment by sinkingsugar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/75?planning-poker) with ZenHub @alebaffa @aang114

**Comment by alebaffa** [comment]
Fixed in PR #96 .
