### ISSUE TITLE
Write Pallet Fragments Tests

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/clamor#78]

**Comment by sinkingsugar** [comment]
Waiting on some bug fixing #102

**Comment by alebaffa** [comment]
There are still few TODOs in pallet fragment tests.

**Comment by aang114** [comment]
The TODOs can only be completed once tickets are implemented. So, I've added #117 as a blocker

**Comment by sinkingsugar** [comment]
@aang114 @alebaffa make a new issues with proper details of actionable items.
