### ISSUE TITLE
Allow filter by generic traits files

### ISSUE THREAD

**Issue by paulinechi** [fragcolor-xyz/clamor#83]
Now when performing get protos by categories, need to pass in the trait name, description and id, would be nicer to allow user to filter by all trait files without specifying details.

**Comment by sinkingsugar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/83?planning-poker) with ZenHub @aang114 @alebaffa
