### ISSUE TITLE
Shouldn't `sender` already be 20 bytes? Why are we doing `sender[12..]`? 

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/clamor#86]
https://github.com/fragcolor-xyz/clamor/blob/e90ff0906cbdb89e7354013a10995cbf3ed18e07/pallets/tickets/src/lib.rs#L601

@sinkingsugar

**Comment by sinkingsugar** [comment]
Ethereum topics/logs are always a fixed 32 bytes, we need to take the last 20 bytes.
