### ISSUE TITLE
`unlink(origin, account)` should not work if ethereum account `account` is not linked to `origin`

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/clamor#89]
https://github.com/fragcolor-xyz/clamor/blob/81b96a78be0223d817ec2c1bc7a13cfb41eb261c/pallets/tickets/src/lib.rs#L366

@sinkingsugar in face I don't understand what's the point of even having the parameter `account`?

- found this bug when writing test cases for Pallet Tickets
  - you can see that the test case `tests::unlink_tests::unlink_should_not_work_if_ethereum_account_id_is_linked_with_different_clamor_account_id` failed

**Comment by sinkingsugar** [comment]
Yes it's bugged, it's missing a check to see if account<->origin exists.
And due to the needed check indeed we can remove `account` as well.
