### ISSUE TITLE
`link(origin, signature)` should not work if recovered ethereum public key is not the intended ethereum public key 

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/clamor#90]
https://github.com/fragcolor-xyz/clamor/blob/81b96a78be0223d817ec2c1bc7a13cfb41eb261c/pallets/tickets/src/lib.rs#L333

- found this while writing tests for Pallet Tickets
  - see the test case `tests::link_tests::link_should_not_work_if_hashed_message_is_invalid`

**Comment by aang114** [comment]
@sinkingsugar   - just to confirm - this is also a bug right? Thanks

**Comment by sinkingsugar** [comment]
Need to actually check
```
ensure!(!<EVMLinks<T>>::contains_key(&sender), Error::<T>::AccountAlreadyLinked);
// WE NEVER DO THIS
ensure!(<EVMLinks<T>>::get(&sender) == eth_key, Error::<T>::AccountAlreadyLinked);
```

**Comment by sinkingsugar** [comment]
As discussed, not a bug.

**Comment by alebaffa** [comment]
Can we close this? @sinkingsugar @aang114

**Comment by sinkingsugar** [comment]
I think so
