### ISSUE TITLE
The `stake()` function will always fail

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/clamor#91]
https://github.com/fragcolor-xyz/clamor/blob/81b96a78be0223d817ec2c1bc7a13cfb41eb261c/pallets/protos/src/lib.rs#L628-L641

@sinkingsugar won't the `stake(who, ...)` function always fail because the `EVMLinks` for `get_locked_frag_account(&who)` was never set previously?

- This bug was found when writing staking-related test cases for Pallet Protos

**Comment by aang114** [comment]
@sinkingsugar , is there any update on this 😅 ? Thanks

**Comment by sinkingsugar** [comment]
We need to rewrite this logic, discuss today. Stake is removed/replaced

**Comment by alebaffa** [comment]
Can we close this since the stake function does not exist anymore? @sinkingsugar @aang114 
Maybe we can open another issue, in case?

**Comment by sinkingsugar** [comment]
Yeah I think it's now irrelevant
