### ISSUE TITLE
Introduce enum to express currency type in Fragment pallet

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#99]
At the moment the FragmentMetadata contains a currency field which can also have two values:
- a currency type 
- None, in case NOVA is used.

```rust
pub struct FragmentMetadata<TFungibleAsset> {
	pub name: Vec<u8>,
	pub currency: Option<TFungibleAsset>, // Where None is NOVA
}
```

This issue is about introducing an enum that can better express this currency choice, and avoid to have None. Something like this:

```rust
enum FragmentCurrency {
  Native, // chain native balance currency
  Custom(AssetID), // assets pallet currency
}
```

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/99?planning-poker) with Zenhub @alebaffa @sinkingsugar
